# Generated by Django 3.0.8 on 2021-01-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ekyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinformation',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kycinformation',
            name='hospital_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kycinformation',
            name='hospital_vacc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.VaccinationOrg'),
        ),
    ]
