# Generated by Django 3.0.8 on 2021-01-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc', '0002_auto_20210129_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinformation',
            name='hospital_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
