# Generated by Django 3.0.8 on 2021-01-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(null=True)),
                ('clicked_photo', models.ImageField(upload_to='uploads/core/clicked_image/')),
                ('user_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.NormalUser')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.IntegerField(choices=[(0, '9:00AM to 10:00AM'), (1, '10:00AM to 11:00AM'), (2, '11:00AM to 12:00AM'), (3, '12:00AM to 1:00PM'), (4, '1:00PM to 2:00PM'), (5, '2:00PM to 3:00PM'), (6, '3:00PM to 4:00PM'), (7, '4:00PM to 5:00PM'), (8, '5:00PM to 6:00PM'), (9, '6:00PM to 7:00PM'), (10, '7:00PM to 8:00PM')], null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.VaccinationOrg')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.NormalUser')),
            ],
        ),
    ]
